reworked docs and made component standards easier to follow/reference
AdaloHQ/docs pull request #80
Opened 2022-05-23 21:32 UTC by TDH55

2022-05-23 21:37 UTC, TDH55 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Component Standards Docs](https://trello.com/c/bLRBblFp/451-component-standards-docs)

2022-05-23 22:09 UTC, nucks requested changes
Left a few comments. Everything else looked good!

2022-05-23 22:09 UTC, nucks commented on website/docs/component-standards/interactions/list-controls.md
> +There are some situations where you should disable list controls, such as sorting and filtering. In general, any time that a list control either doesn't make sense in the context of you're component
```suggestion
There are some situations where you should disable list controls, such as sorting and filtering. In general, any time that a list control either doesn't make sense in the context of your component or doesn't have any effect on how the component is rendered, then the control should be disabled.
```

2022-05-23 22:09 UTC, nucks commented on website/docs/component-standards/code/external-apis.md
> +The use of 3rd party APIs in your components is allowed, but you should be aware of the license and attribution requirements of all APIs you use. 3rd party APIs should also be reputable, well maintai
```suggestion
The use of 3rd-party APIs in your components is allowed, but you should be aware of the license and attribution requirements of all APIs you use. 3rd-party APIs should also be reputable, well maintained, and not introduce any security vulnerabilities to makers, end users, or the Adalo ecosystem as a whole. If you are unsure of the license or attribution requirements of an API, or whether or not an API is reputable, please contact the Adalo team.
```

2022-05-23 22:25 UTC, adebroux requested changes
Looks great! Just a few minor grammar/wording suggestions

2022-05-23 22:25 UTC, adebroux commented on website/docs/component-standards/interactions/child-components.md
> +* Should be able to be enabled and disabled when applicable. See [conditional control](docs/interactions/conditional-control)
```suggestion
* Be able to be enabled and disabled when applicable. See [conditional control](docs/interactions/conditional-control)
```

2022-05-23 22:25 UTC, adebroux commented on website/docs/component-standards/interactions/exporting-data.md
> +Component data allows props from your component to be accessed via magic text in other components, as well as your own. This should be considered the default method for exporting data and should be u
Need the rest of this sentence!

2022-05-23 22:25 UTC, adebroux commented on website/docs/component-standards/interactions/exporting-data.md
> +Action arguments are very similar to component data, they allow you to use information from your component within an action **in your component only**. One instance where this is useful is when you w
```suggestion
Action arguments are very similar to component data. They allow you to use information from your component within an action **in your component only**. This is useful if you want to use information from your component in an action, but don't want to share that information across the entire Adalo ecosystem.
```

2022-05-23 22:25 UTC, adebroux commented on website/docs/component-standards/interactions/list-controls.md
> +There are some situations where you should disable list controls, such as sorting and filtering. In general, any time that a list control either doesn't make sense in the context of your component or
```suggestion
There are some situations where you should disable list controls, such as sorting and filtering. In general, if a list control either doesn't make sense in the context of your component or doesn't have any effect on how the component is rendered, the control should be disabled.
```

2022-05-23 22:25 UTC, adebroux commented on website/docs/component-standards/component-listing/logo.md
> +The logo in the marketplace is a chance for you to show off your component in a branded way. So while the thumbnail is meant to be a representation of what will actually show up when it’s in the app,
```suggestion
The logo in the marketplace is a chance for you to show off your component in a branded way. So while the thumbnail is meant to be a representation of what will actually show up in the app, the logo is more of an icon. And it's a chance for you to have a little more fun!
```

2022-05-23 22:25 UTC, adebroux commented on website/docs/component-standards/code/performance.md
> +- Excessive api calls
```suggestion
- Excessive API calls
```

2022-05-24 15:27 UTC, TDH55 commented on website/docs/component-standards/interactions/exporting-data.md
> +Component data allows props from your component to be accessed via magic text in other components, as well as your own. This should be considered the default method for exporting data and should be u
I was going to add something about action arguments but I think it's best to end there.

2022-05-24 16:41 UTC, adebroux commented on website/docs/component-standards/configuration/package-json.md
> +Once you have published your library you can **NOT** change your library name.
That's fair! I think we still might want to add a note that you also can't change the description once it's published, just so developers don't get stuck with a placeholder description.

2022-05-24 16:50 UTC, TDH55 commented on website/docs/component-standards/configuration/package-json.md
> +Once you have published your library you can **NOT** change your library name.
It actually looks like we can change the description now so I'm going to leave this as is

2022-05-24 18:03 UTC, merged